# Generated by Django 6.0.6 on 2026-07-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elon',
            old_name='xolot',
            new_name='xolat',
        ),
    ]
