# Generated by Django 6.0.6 on 2026-07-01 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0002_rename_xolot_elon_xolat'),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='elons', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
